//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAVINGS_v1.Resources.CreateProposal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateProposal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateProposal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESAVINGS_v1.Resources.CreateProposal.CreateProposal", typeof(CreateProposal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Description (Computed Cost reduction / Cost Avoidance).
        /// </summary>
        public static string AdditionalDescriptionLbl {
            get {
                return ResourceManager.GetString("AdditionalDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose department/area beneficiary of your project.
        /// </summary>
        public static string ChooseDeptAreaBeneficiaryLbl {
            get {
                return ResourceManager.GetString("ChooseDeptAreaBeneficiaryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Proposal.
        /// </summary>
        public static string CreateProposalLbl {
            get {
                return ResourceManager.GetString("CreateProposalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Description.
        /// </summary>
        public static string CurrentDescriptionLbl {
            get {
                return ResourceManager.GetString("CurrentDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentLbl {
            get {
                return ResourceManager.GetString("CurrentLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLbl {
            get {
                return ResourceManager.GetString("DeleteLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department/Area beneficiary.
        /// </summary>
        public static string DeptAreaBeneficiaryLbl {
            get {
                return ResourceManager.GetString("DeptAreaBeneficiaryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar Impact.
        /// </summary>
        public static string DollarImpactLbl {
            get {
                return ResourceManager.GetString("DollarImpactLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit proposal images.
        /// </summary>
        public static string EditProposalImgsHeader {
            get {
                return ResourceManager.GetString("EditProposalImgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected number of months to be active.
        /// </summary>
        public static string ExpectedNumOfMonthsToBeActiveLbl {
            get {
                return ResourceManager.GetString("ExpectedNumOfMonthsToBeActiveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected start date.
        /// </summary>
        public static string ExpectedStartDateLbl {
            get {
                return ResourceManager.GetString("ExpectedStartDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string FilenameLbl {
            get {
                return ResourceManager.GetString("FilenameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title.
        /// </summary>
        public static string ProjectTitleLbl {
            get {
                return ResourceManager.GetString("ProjectTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string ProjectTypeLbl {
            get {
                return ResourceManager.GetString("ProjectTypeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal Description.
        /// </summary>
        public static string ProposalDescriptionLbl {
            get {
                return ResourceManager.GetString("ProposalDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string ProposalLbl {
            get {
                return ResourceManager.GetString("ProposalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string RemarksLbl {
            get {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANK YOU FOR PARTICIPATING ON THE COST-SAVING CAMPAIGN!.
        /// </summary>
        public static string SubmissionConfirmationHeader {
            get {
                return ResourceManager.GetString("SubmissionConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your proposal was submitted successfully. Expect an email notification everytime your proposal changes status or the approvers assign an action item..
        /// </summary>
        public static string SubmissionConfirmationMsg {
            get {
                return ResourceManager.GetString("SubmissionConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitBtnLbl {
            get {
                return ResourceManager.GetString("SubmitBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Documents.
        /// </summary>
        public static string SupportingDocumentsLbl {
            get {
                return ResourceManager.GetString("SupportingDocumentsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Proposal.
        /// </summary>
        public static string UpdateProposalLbl {
            get {
                return ResourceManager.GetString("UpdateProposalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadBtnLbl {
            get {
                return ResourceManager.GetString("UploadBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetailsBtnLbl {
            get {
                return ResourceManager.GetString("ViewDetailsBtnLbl", resourceCulture);
            }
        }
    }
}
