//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAVINGS_v1.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Base {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Base() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESAVINGS_v1.Resources.Controllers.Base", typeof(Base).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        internal static string directory_not_found {
            get {
                return ResourceManager.GetString("directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found.
        /// </summary>
        internal static string error_found {
            get {
                return ResourceManager.GetString("error_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is invalid (Not allowed to upload).
        /// </summary>
        internal static string file_is_invalid_not_allowed_to_upload {
            get {
                return ResourceManager.GetString("file_is_invalid_not_allowed_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string file_not_found {
            get {
                return ResourceManager.GetString("file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document type (expected file is {0}).
        /// </summary>
        internal static string invalid_doc_type_expected_file_is {
            get {
                return ResourceManager.GetString("invalid_doc_type_expected_file_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document type (Not allowed to upload).
        /// </summary>
        internal static string invalid_doc_type_not_allowed_to_upload {
            get {
                return ResourceManager.GetString("invalid_doc_type_not_allowed_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file size.
        /// </summary>
        internal static string invalid_file_size {
            get {
                return ResourceManager.GetString("invalid_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type (Not allowed to upload).
        /// </summary>
        internal static string invalid_img_type_not_allowed_to_upload {
            get {
                return ResourceManager.GetString("invalid_img_type_not_allowed_to_upload", resourceCulture);
            }
        }
    }
}
