//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAVINGS_v1.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ESavings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ESavings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESAVINGS_v1.Resources.Controllers.ESavings", typeof(ESavings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the requirements, (Remarks and verification status).
        /// </summary>
        internal static string action_approval_complete_reqmts_msg {
            get {
                return ResourceManager.GetString("action_approval_complete_reqmts_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0}. {1} by {2}. &lt;br/&gt;Please click the link below to view the details..
        /// </summary>
        internal static string action_approval_email_msg {
            get {
                return ResourceManager.GetString("action_approval_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added dollar impact.
        /// </summary>
        internal static string added_dollar_impact {
            get {
                return ResourceManager.GetString("added_dollar_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added expected project start date.
        /// </summary>
        internal static string added_expected_project_start_date {
            get {
                return ResourceManager.GetString("added_expected_project_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added finance approver.
        /// </summary>
        internal static string added_finance_approver {
            get {
                return ResourceManager.GetString("added_finance_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added number of months to be active.
        /// </summary>
        internal static string added_number_of_months_active {
            get {
                return ResourceManager.GetString("added_number_of_months_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added project type.
        /// </summary>
        internal static string added_project_type {
            get {
                return ResourceManager.GetString("added_project_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area/Department Beneficiary.
        /// </summary>
        internal static string area_dept {
            get {
                return ResourceManager.GetString("area_dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the requirements, (project owner ff id, fullname and proposal id).
        /// </summary>
        internal static string assign_project_owner_complete_reqmnts_msg {
            get {
                return ResourceManager.GetString("assign_project_owner_complete_reqmnts_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0} - assigned you as project owner (who execute the project). Please click the link below to view the details &lt;br/&gt;.
        /// </summary>
        internal static string assign_project_owner_email_msg {
            get {
                return ResourceManager.GetString("assign_project_owner_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner in E-Savings-Ticket#.
        /// </summary>
        internal static string assign_project_owner_email_subject {
            get {
                return ResourceManager.GetString("assign_project_owner_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign project owner, please try again.
        /// </summary>
        internal static string assign_project_owner_error_msg {
            get {
                return ResourceManager.GetString("assign_project_owner_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully assign to project owner.
        /// </summary>
        internal static string assign_project_owner_success_msg {
            get {
                return ResourceManager.GetString("assign_project_owner_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign new cost analyst approver.
        /// </summary>
        internal static string assigned_new_cost_analyst_approver {
            get {
                return ResourceManager.GetString("assigned_new_cost_analyst_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked.
        /// </summary>
        internal static string bpi_marked {
            get {
                return ResourceManager.GetString("bpi_marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmarked.
        /// </summary>
        internal static string bpi_unmarked {
            get {
                return ResourceManager.GetString("bpi_unmarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Analyst approver is not allowed to make changes on this approval.
        /// </summary>
        internal static string CA_approver_not_allowed_to_make_changes_on_this {
            get {
                return ResourceManager.GetString("CA_approver_not_allowed_to_make_changes_on_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all action items before moving the active.
        /// </summary>
        internal static string close_all_action_items_before_move_to_active {
            get {
                return ResourceManager.GetString("close_all_action_items_before_move_to_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all action items before moving the status to finance approval.
        /// </summary>
        internal static string close_all_action_items_before_move_to_finance_approval {
            get {
                return ResourceManager.GetString("close_all_action_items_before_move_to_finance_approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all action items before moving the cost funnel evaluating.
        /// </summary>
        internal static string close_all_action_items_before_move_to_funnel_evaluating {
            get {
                return ResourceManager.GetString("close_all_action_items_before_move_to_funnel_evaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0}. {1} by {2}. &lt;br/&gt;Please click the link below to view the details..
        /// </summary>
        internal static string cost_analyst_approval_email_msg_1 {
            get {
                return ResourceManager.GetString("cost_analyst_approval_email_msg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0}. Moved status to {1} by {2}. Please click the link below to view the details.
        /// </summary>
        internal static string cost_analyst_approval_email_msg_2 {
            get {
                return ResourceManager.GetString("cost_analyst_approval_email_msg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0}. {1} by {2}. Need your approval, please click the link below to view the details..
        /// </summary>
        internal static string cost_analyst_approval_email_msg_3 {
            get {
                return ResourceManager.GetString("cost_analyst_approval_email_msg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings-Move-status-Ticket#{0}.
        /// </summary>
        internal static string cost_analyst_approval_email_subject_2 {
            get {
                return ResourceManager.GetString("cost_analyst_approval_email_subject_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully moved status to &lt;i&gt;{0}&lt;/i&gt; status!.
        /// </summary>
        internal static string cost_analyst_approval_successes_msg {
            get {
                return ResourceManager.GetString("cost_analyst_approval_successes_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the requirements, (Action Description and action owner info).
        /// </summary>
        internal static string create_new_action_complete_reqmts_msg {
            get {
                return ResourceManager.GetString("create_new_action_complete_reqmts_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Needed from E-Savings Ticket #{0} is assign to you. Please click the link below to view the details.
        /// </summary>
        internal static string create_new_action_email_msg {
            get {
                return ResourceManager.GetString("create_new_action_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Needed from E-Savings-Ticket#.
        /// </summary>
        internal static string create_new_action_email_subject {
            get {
                return ResourceManager.GetString("create_new_action_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new action, please try again.
        /// </summary>
        internal static string create_new_action_error_msg {
            get {
                return ResourceManager.GetString("create_new_action_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action successfully assign to action owner.
        /// </summary>
        internal static string create_new_action_success_msg {
            get {
                return ResourceManager.GetString("create_new_action_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current description.
        /// </summary>
        internal static string current_description {
            get {
                return ResourceManager.GetString("current_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Images (Unable to upload).
        /// </summary>
        internal static string current_imgs_unable_upload {
            get {
                return ResourceManager.GetString("current_imgs_unable_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target.
        /// </summary>
        internal static string delete_proposal_files_invalid_target {
            get {
                return ResourceManager.GetString("delete_proposal_files_invalid_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar impact.
        /// </summary>
        internal static string dollar_impact {
            get {
                return ResourceManager.GetString("dollar_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar impact is required.
        /// </summary>
        internal static string dollar_impact_is_required {
            get {
                return ResourceManager.GetString("dollar_impact_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done adding finance approver.
        /// </summary>
        internal static string done_adding_finance_approver {
            get {
                return ResourceManager.GetString("done_adding_finance_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done changing finance approver..
        /// </summary>
        internal static string done_changing_finance_approver {
            get {
                return ResourceManager.GetString("done_changing_finance_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected start date.
        /// </summary>
        internal static string expected_start_date {
            get {
                return ResourceManager.GetString("expected_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected start date is required.
        /// </summary>
        internal static string expected_start_date_is_required {
            get {
                return ResourceManager.GetString("expected_start_date_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0}. {1} by {2}. &lt;br/&gt;Please click the link below to view the details..
        /// </summary>
        internal static string finance_approval_email_msg {
            get {
                return ResourceManager.GetString("finance_approval_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully moved status to &lt;i&gt;{0}&lt;/i&gt; status!.
        /// </summary>
        internal static string finance_approval_success_msg {
            get {
                return ResourceManager.GetString("finance_approval_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, kindly report this error.
        /// </summary>
        internal static string internal_error_msg {
            get {
                return ResourceManager.GetString("internal_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current image length.
        /// </summary>
        internal static string invalid_current_img_len {
            get {
                return ResourceManager.GetString("invalid_current_img_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department/Area beneficiary.
        /// </summary>
        internal static string invalid_dept_area_beneficiary {
            get {
                return ResourceManager.GetString("invalid_dept_area_beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dollar impact.
        /// </summary>
        internal static string invalid_dollar_impact {
            get {
                return ResourceManager.GetString("invalid_dollar_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dollar impact (must be whole/decimal number).
        /// </summary>
        internal static string invalid_dollar_impact_whole_decimal_num {
            get {
                return ResourceManager.GetString("invalid_dollar_impact_whole_decimal_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expected start date.
        /// </summary>
        internal static string invalid_expected_start_date {
            get {
                return ResourceManager.GetString("invalid_expected_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of months to be active.
        /// </summary>
        internal static string invalid_num_months_to_be_active {
            get {
                return ResourceManager.GetString("invalid_num_months_to_be_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of months to be active (less than or equal to {0} OR greater than {1} only).
        /// </summary>
        internal static string invalid_num_months_to_be_active_less_greater_than {
            get {
                return ResourceManager.GetString("invalid_num_months_to_be_active_less_greater_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OA status.
        /// </summary>
        internal static string invalid_oa_status {
            get {
                return ResourceManager.GetString("invalid_oa_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project type.
        /// </summary>
        internal static string invalid_project_type {
            get {
                return ResourceManager.GetString("invalid_project_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Proposal.
        /// </summary>
        internal static string invalid_proposal {
            get {
                return ResourceManager.GetString("invalid_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proposal id.
        /// </summary>
        internal static string invalid_proposal_id {
            get {
                return ResourceManager.GetString("invalid_proposal_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proposal image length.
        /// </summary>
        internal static string invalid_proposal_img_len {
            get {
                return ResourceManager.GetString("invalid_proposal_img_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Status.
        /// </summary>
        internal static string invalid_status {
            get {
                return ResourceManager.GetString("invalid_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid supporting documents length.
        /// </summary>
        internal static string invalid_supporting_docs_len {
            get {
                return ResourceManager.GetString("invalid_supporting_docs_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification status indicator.
        /// </summary>
        internal static string invalid_verification_status {
            get {
                return ResourceManager.GetString("invalid_verification_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings proposal Ticket #{0} Marked as BPI. Please click the link below to view the details..
        /// </summary>
        internal static string mark_proposal_bpi_email_msg {
            get {
                return ResourceManager.GetString("mark_proposal_bpi_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings project marked as BPI.
        /// </summary>
        internal static string mark_proposal_bpi_email_subject {
            get {
                return ResourceManager.GetString("mark_proposal_bpi_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: unable to {0} proposal as BPI.
        /// </summary>
        internal static string mark_proposal_bpi_error_msg {
            get {
                return ResourceManager.GetString("mark_proposal_bpi_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} proposal as BPI.
        /// </summary>
        internal static string mark_proposal_bpi_success_msg {
            get {
                return ResourceManager.GetString("mark_proposal_bpi_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes made.
        /// </summary>
        internal static string no_changes_made {
            get {
                return ResourceManager.GetString("no_changes_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-verification.
        /// </summary>
        internal static string no_verification {
            get {
                return ResourceManager.GetString("no_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of months to be active.
        /// </summary>
        internal static string number_of_months_active {
            get {
                return ResourceManager.GetString("number_of_months_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of months to be active is required.
        /// </summary>
        internal static string number_of_months_active_required {
            get {
                return ResourceManager.GetString("number_of_months_active_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string permission_denied {
            get {
                return ResourceManager.GetString("permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login.
        /// </summary>
        internal static string please_login {
            get {
                return ResourceManager.GetString("please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select finance approver.
        /// </summary>
        internal static string please_select_finance_approver {
            get {
                return ResourceManager.GetString("please_select_finance_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id.
        /// </summary>
        internal static string project_id {
            get {
                return ResourceManager.GetString("project_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title.
        /// </summary>
        internal static string project_title {
            get {
                return ResourceManager.GetString("project_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        internal static string project_type {
            get {
                return ResourceManager.GetString("project_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type is required.
        /// </summary>
        internal static string project_type_is_required {
            get {
                return ResourceManager.GetString("project_type_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal description.
        /// </summary>
        internal static string proposal_description {
            get {
                return ResourceManager.GetString("proposal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal details not found.
        /// </summary>
        internal static string proposal_details_not_found {
            get {
                return ResourceManager.GetString("proposal_details_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal entry not found!.
        /// </summary>
        internal static string proposal_entry_not_found {
            get {
                return ResourceManager.GetString("proposal_entry_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal Images (Unable to upload).
        /// </summary>
        internal static string proposal_imgs_unable_upload {
            get {
                return ResourceManager.GetString("proposal_imgs_unable_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings ticket#{0}, is re-assign to you as cost-analyst approver by {1}. Please click the link below to view the details.
        /// </summary>
        internal static string re_assign_project_CA_email_msg {
            get {
                return ResourceManager.GetString("re_assign_project_CA_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on assigning new cost-analyst, please contact site admin.
        /// </summary>
        internal static string re_assign_project_CA_error_msg {
            get {
                return ResourceManager.GetString("re_assign_project_CA_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully assigned new cost-analyst.
        /// </summary>
        internal static string re_assign_project_CA_success_msg {
            get {
                return ResourceManager.GetString("re_assign_project_CA_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings ticket#{0}, is re-assign to you as finance approver by {1}. Please click the link below to view the details.
        /// </summary>
        internal static string re_assign_project_finance_email_msg {
            get {
                return ResourceManager.GetString("re_assign_project_finance_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on assigning new finance, please contact site admin.
        /// </summary>
        internal static string re_assign_project_finance_error_msg {
            get {
                return ResourceManager.GetString("re_assign_project_finance_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully assigned new finance.
        /// </summary>
        internal static string re_assign_project_finance_success_msg {
            get {
                return ResourceManager.GetString("re_assign_project_finance_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks is required.
        /// </summary>
        internal static string remarks_is_required {
            get {
                return ResourceManager.GetString("remarks_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the requirements, (Remarks and supporting documents).
        /// </summary>
        internal static string save_action_owner_response_complete_reqmts_msg {
            get {
                return ResourceManager.GetString("save_action_owner_response_complete_reqmts_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0} Action item responded by action owner {1}. Please click the link below to view the details.
        /// </summary>
        internal static string save_action_owner_response_email_msg {
            get {
                return ResourceManager.GetString("save_action_owner_response_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Needed from E-Savings-Ticket#.
        /// </summary>
        internal static string save_action_owner_response_email_subject {
            get {
                return ResourceManager.GetString("save_action_owner_response_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Ticket #{0} - Project owner responded [{1}]. Please click the link below to view the details.
        /// </summary>
        internal static string save_project_owner_response_email_msg {
            get {
                return ResourceManager.GetString("save_project_owner_response_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner from E-Savings-Ticket#.
        /// </summary>
        internal static string save_project_owner_response_email_subject {
            get {
                return ResourceManager.GetString("save_project_owner_response_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected finance approver not found.
        /// </summary>
        internal static string selected_finance_approver_not_found {
            get {
                return ResourceManager.GetString("selected_finance_approver_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings NEW proposal Ticket #{0}. Please click the link below to view the details.
        /// </summary>
        internal static string submit_proposal_email_msg {
            get {
                return ResourceManager.GetString("submit_proposal_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New E-Savings Entry.
        /// </summary>
        internal static string submit_proposal_email_subject {
            get {
                return ResourceManager.GetString("submit_proposal_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error submitting your proposal, kindly contact APPs team to check the error, Thank you!.
        /// </summary>
        internal static string submit_proposal_error_msg {
            get {
                return ResourceManager.GetString("submit_proposal_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        internal static string successfully_deleted {
            get {
                return ResourceManager.GetString("successfully_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Saved!.
        /// </summary>
        internal static string successfully_saved {
            get {
                return ResourceManager.GetString("successfully_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully submitted.
        /// </summary>
        internal static string successfully_submitted {
            get {
                return ResourceManager.GetString("successfully_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        internal static string successfully_updated {
            get {
                return ResourceManager.GetString("successfully_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded.
        /// </summary>
        internal static string successfully_uploaded {
            get {
                return ResourceManager.GetString("successfully_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully verified!.
        /// </summary>
        internal static string successfully_verified {
            get {
                return ResourceManager.GetString("successfully_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Images (Unable to upload).
        /// </summary>
        internal static string supporting_docs_unable_upload {
            get {
                return ResourceManager.GetString("supporting_docs_unable_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting documents uploaded.
        /// </summary>
        internal static string supporting_docs_uploaded {
            get {
                return ResourceManager.GetString("supporting_docs_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: trying to assign current approver.
        /// </summary>
        internal static string trying_to_assign_current_approver {
            get {
                return ResourceManager.GetString("trying_to_assign_current_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add finance approver.
        /// </summary>
        internal static string unable_to_add_finance_approver {
            get {
                return ResourceManager.GetString("unable_to_add_finance_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add/update dollar impact.
        /// </summary>
        internal static string unable_to_add_update_dollar_impact {
            get {
                return ResourceManager.GetString("unable_to_add_update_dollar_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add/update expected project start date.
        /// </summary>
        internal static string unable_to_add_update_expected_project_start_date {
            get {
                return ResourceManager.GetString("unable_to_add_update_expected_project_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add/update number of months to be active.
        /// </summary>
        internal static string unable_to_add_update_number_months_active {
            get {
                return ResourceManager.GetString("unable_to_add_update_number_months_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add/update project type.
        /// </summary>
        internal static string unable_to_add_update_project_type {
            get {
                return ResourceManager.GetString("unable_to_add_update_project_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reassign finance approver.
        /// </summary>
        internal static string unable_to_reassign_finance_approver {
            get {
                return ResourceManager.GetString("unable_to_reassign_finance_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update overall status ({0}).
        /// </summary>
        internal static string unable_to_update_overall_status_to {
            get {
                return ResourceManager.GetString("unable_to_update_overall_status_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify this proposal.
        /// </summary>
        internal static string unable_to_verify_this_proposal {
            get {
                return ResourceManager.GetString("unable_to_verify_this_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update verification results.
        /// </summary>
        internal static string unable_update_verification_results {
            get {
                return ResourceManager.GetString("unable_update_verification_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update dollar impact.
        /// </summary>
        internal static string update_dollar_impact {
            get {
                return ResourceManager.GetString("update_dollar_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update number of months to be active.
        /// </summary>
        internal static string update_number_of_months_active {
            get {
                return ResourceManager.GetString("update_number_of_months_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings proposal Ticket #{0} - Updated by {1}. &lt;br/&gt;Please click the link below to view the details.
        /// </summary>
        internal static string update_proposal_email_msg {
            get {
                return ResourceManager.GetString("update_proposal_email_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Savings Entry Updated.
        /// </summary>
        internal static string update_proposal_email_subject {
            get {
                return ResourceManager.GetString("update_proposal_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update your proposal details.
        /// </summary>
        internal static string update_proposal_error_msg {
            get {
                return ResourceManager.GetString("update_proposal_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Actual completion date.
        /// </summary>
        internal static string updated_actual_completion_date {
            get {
                return ResourceManager.GetString("updated_actual_completion_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Current due date.
        /// </summary>
        internal static string updated_current_due_date {
            get {
                return ResourceManager.GetString("updated_current_due_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Finance category.
        /// </summary>
        internal static string updated_finance_category {
            get {
                return ResourceManager.GetString("updated_finance_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated funnel status.
        /// </summary>
        internal static string updated_funnel_status {
            get {
                return ResourceManager.GetString("updated_funnel_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Original due date.
        /// </summary>
        internal static string updated_original_due_date {
            get {
                return ResourceManager.GetString("updated_original_due_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Planned project start date.
        /// </summary>
        internal static string updated_planned_project_start_date {
            get {
                return ResourceManager.GetString("updated_planned_project_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Planned saving start date.
        /// </summary>
        internal static string updated_planned_saving_start_date {
            get {
                return ResourceManager.GetString("updated_planned_saving_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification status not found.
        /// </summary>
        internal static string verification_status_not_found {
            get {
                return ResourceManager.GetString("verification_status_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string verified {
            get {
                return ResourceManager.GetString("verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified closed.
        /// </summary>
        internal static string verified_closed {
            get {
                return ResourceManager.GetString("verified_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify not done.
        /// </summary>
        internal static string verify_not_done {
            get {
                return ResourceManager.GetString("verify_not_done", resourceCulture);
            }
        }
    }
}
