//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.DomainResources", typeof(DomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        internal static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELED.
        /// </summary>
        internal static string CANCELED {
            get {
                return ResourceManager.GetString("CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        internal static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COST-ANALYST-REVIEW-IN-PROGRESS.
        /// </summary>
        internal static string COST_ANALYST_REVIEW_IN_PROGRESS {
            get {
                return ResourceManager.GetString("COST_ANALYST_REVIEW_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COST-AVOIDANCE.
        /// </summary>
        internal static string COST_AVOIDANCE {
            get {
                return ResourceManager.GetString("COST_AVOIDANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COST-FUNNEL-EVALUATING.
        /// </summary>
        internal static string COST_FUNNEL_EVALUATING {
            get {
                return ResourceManager.GetString("COST_FUNNEL_EVALUATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCE-PENDING.
        /// </summary>
        internal static string COST_FUNNEL_IDENTIFIED {
            get {
                return ResourceManager.GetString("COST_FUNNEL_IDENTIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COST-SAVINGS.
        /// </summary>
        internal static string COST_SAVINGS {
            get {
                return ResourceManager.GetString("COST_SAVINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Analyst.
        /// </summary>
        internal static string CostAnalyst {
            get {
                return ResourceManager.GetString("CostAnalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Funnel Evaluation.
        /// </summary>
        internal static string CostFunnelEvaluation {
            get {
                return ResourceManager.GetString("CostFunnelEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Funnel Identified.
        /// </summary>
        internal static string CostFunnelIdentified {
            get {
                return ResourceManager.GetString("CostFunnelIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost site incharge.
        /// </summary>
        internal static string CostSiteInCharge {
            get {
                return ResourceManager.GetString("CostSiteInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUPLICATE-ENTRY.
        /// </summary>
        internal static string DUPLICATE_ENTRY {
            get {
                return ResourceManager.GetString("DUPLICATE_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXISTING-PROJECT.
        /// </summary>
        internal static string EXISTING_PROJECT {
            get {
                return ResourceManager.GetString("EXISTING_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCE-REVIEW-IN-PROGRESS.
        /// </summary>
        internal static string FINANCE_REVIEW_IN_PROGRESS {
            get {
                return ResourceManager.GetString("FINANCE_REVIEW_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Progress Action Required.
        /// </summary>
        internal static string INProgressActionRequired {
            get {
                return ResourceManager.GetString("INProgressActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID.
        /// </summary>
        internal static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Account.
        /// </summary>
        internal static string MasterAccount {
            get {
                return ResourceManager.GetString("MasterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Entry.
        /// </summary>
        internal static string NewProductEntry {
            get {
                return ResourceManager.GetString("NewProductEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT-PROPOSAL.
        /// </summary>
        internal static string PROJECT_PROPOSAL {
            get {
                return ResourceManager.GetString("PROJECT_PROPOSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REALIZATION.
        /// </summary>
        internal static string REALIZATION {
            get {
                return ResourceManager.GetString("REALIZATION", resourceCulture);
            }
        }
    }
}
