//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAVINGS_v1.Resources.Details {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESAVINGS_v1.Resources.Details.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action description.
        /// </summary>
        public static string ActionDescriptionLbl {
            get {
                return ResourceManager.GetString("ActionDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Item.
        /// </summary>
        public static string ActionItemTabHeader {
            get {
                return ResourceManager.GetString("ActionItemTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Date.
        /// </summary>
        public static string ActionVerificationDateLbl {
            get {
                return ResourceManager.GetString("ActionVerificationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Status.
        /// </summary>
        public static string ActionVerificationStatusLbl {
            get {
                return ResourceManager.GetString("ActionVerificationStatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Done.
        /// </summary>
        public static string ActionVerifyDoneBtnLbl {
            get {
                return ResourceManager.GetString("ActionVerifyDoneBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Not Done.
        /// </summary>
        public static string ActionVerifyNotDoneBtnLbl {
            get {
                return ResourceManager.GetString("ActionVerifyNotDoneBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveBtnLbl {
            get {
                return ResourceManager.GetString("ActiveBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Description (Computed Cost reduction / Cost Avoidance).
        /// </summary>
        public static string AdditionalDescriptionLbl {
            get {
                return ResourceManager.GetString("AdditionalDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-verification.
        /// </summary>
        public static string ApprovalStatus_NoVerification {
            get {
                return ResourceManager.GetString("ApprovalStatus_NoVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified-closed.
        /// </summary>
        public static string ApprovalStatus_VerifiedClosed {
            get {
                return ResourceManager.GetString("ApprovalStatus_VerifiedClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify-no-done.
        /// </summary>
        public static string ApprovalStatus_VerifyNotDone {
            get {
                return ResourceManager.GetString("ApprovalStatus_VerifyNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval status.
        /// </summary>
        public static string ApprovalStatusTabHeader {
            get {
                return ResourceManager.GetString("ApprovalStatusTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string ApproverNameLbl {
            get {
                return ResourceManager.GetString("ApproverNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string ApproverRemarksLbl {
            get {
                return ResourceManager.GetString("ApproverRemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign action.
        /// </summary>
        public static string AssignActionBtnLbl {
            get {
                return ResourceManager.GetString("AssignActionBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign action owner.
        /// </summary>
        public static string AssignActionOwnerModalHeader {
            get {
                return ResourceManager.GetString("AssignActionOwnerModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string AssignBtnLbl {
            get {
                return ResourceManager.GetString("AssignBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Date.
        /// </summary>
        public static string AssignedDatelbl {
            get {
                return ResourceManager.GetString("AssignedDatelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee Section.
        /// </summary>
        public static string AssigneedSectionHeader {
            get {
                return ResourceManager.GetString("AssigneedSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached By.
        /// </summary>
        public static string AttachedByTbHeader {
            get {
                return ResourceManager.GetString("AttachedByTbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Section.
        /// </summary>
        public static string AttachmentSectionHeader {
            get {
                return ResourceManager.GetString("AttachmentSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachmentTabHeader {
            get {
                return ResourceManager.GetString("AttachmentTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Practice Implementation.
        /// </summary>
        public static string BestPracticeImplementation {
            get {
                return ResourceManager.GetString("BestPracticeImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtnLbl {
            get {
                return ResourceManager.GetString("CancelBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Cost-Analyst.
        /// </summary>
        public static string ChangeCostAnalystLbl {
            get {
                return ResourceManager.GetString("ChangeCostAnalystLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeFinanceLbl.
        /// </summary>
        public static string ChangeFinanceLbl {
            get {
                return ResourceManager.GetString("ChangeFinanceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action owner.
        /// </summary>
        public static string ChooseActionOwnerLbl {
            get {
                return ResourceManager.GetString("ChooseActionOwnerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose cost-analyst approver.
        /// </summary>
        public static string ChooseCostAnalystApproverLbl {
            get {
                return ResourceManager.GetString("ChooseCostAnalystApproverLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseFinanceApproverLbl.
        /// </summary>
        public static string ChooseFinanceApproverLbl {
            get {
                return ResourceManager.GetString("ChooseFinanceApproverLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Update.
        /// </summary>
        public static string ContinueUpdateBtnLbl {
            get {
                return ResourceManager.GetString("ContinueUpdateBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost-Analyst.
        /// </summary>
        public static string CostAnalystApproverLbl {
            get {
                return ResourceManager.GetString("CostAnalystApproverLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Date.
        /// </summary>
        public static string CostAnalystVerifiedDateLbl {
            get {
                return ResourceManager.GetString("CostAnalystVerifiedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Status.
        /// </summary>
        public static string CostAnalystVerifiedStatusLbl {
            get {
                return ResourceManager.GetString("CostAnalystVerifiedStatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Funnel Evaluating.
        /// </summary>
        public static string CostFunnelEvaluatingBtnLbl {
            get {
                return ResourceManager.GetString("CostFunnelEvaluatingBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CurrentCostAnalystRemarksLbl {
            get {
                return ResourceManager.GetString("CurrentCostAnalystRemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentDescLbl {
            get {
                return ResourceManager.GetString("CurrentDescLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date submitted.
        /// </summary>
        public static string DateSubmittedLbl {
            get {
                return ResourceManager.GetString("DateSubmittedLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department / Area beneficiary.
        /// </summary>
        public static string DepartmentAreaBeneficiaryLbl {
            get {
                return ResourceManager.GetString("DepartmentAreaBeneficiaryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Cost Analyst Section.
        /// </summary>
        public static string DeptCostAnalystSectionHeader {
            get {
                return ResourceManager.GetString("DeptCostAnalystSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar Impact.
        /// </summary>
        public static string DollarImpactLbl {
            get {
                return ResourceManager.GetString("DollarImpactLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Entry.
        /// </summary>
        public static string DuplicateEntryBtnLbl {
            get {
                return ResourceManager.GetString("DuplicateEntryBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Initiator.
        /// </summary>
        public static string EmployeeNameLbl {
            get {
                return ResourceManager.GetString("EmployeeNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Project.
        /// </summary>
        public static string ExistingProjectBtnLbl {
            get {
                return ResourceManager.GetString("ExistingProjectBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Start Date.
        /// </summary>
        public static string ExpectedStartDateLbl {
            get {
                return ResourceManager.GetString("ExpectedStartDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileNameTbHeader {
            get {
                return ResourceManager.GetString("FileNameTbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Approval.
        /// </summary>
        public static string FinanceApprovalLbl {
            get {
                return ResourceManager.GetString("FinanceApprovalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Approver.
        /// </summary>
        public static string FinanceApproverLbl {
            get {
                return ResourceManager.GetString("FinanceApproverLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Category.
        /// </summary>
        public static string FinanceCategoryLbl {
            get {
                return ResourceManager.GetString("FinanceCategoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Section.
        /// </summary>
        public static string FinanceSectionHeader {
            get {
                return ResourceManager.GetString("FinanceSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string InvalidBtnLbl {
            get {
                return ResourceManager.GetString("InvalidBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Marked as Best practice implementation **.
        /// </summary>
        public static string MarkAsBPI {
            get {
                return ResourceManager.GetString("MarkAsBPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthLbl {
            get {
                return ResourceManager.GetString("MonthLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed action.
        /// </summary>
        public static string NeededActionLbl {
            get {
                return ResourceManager.GetString("NeededActionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS NO ATTACHMENT AT THE MOMENT.
        /// </summary>
        public static string NoAttachMsg {
            get {
                return ResourceManager.GetString("NoAttachMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of months to be active.
        /// </summary>
        public static string NumberOfMonthsToBeActiveLbl {
            get {
                return ResourceManager.GetString("NumberOfMonthsToBeActiveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTabHeader {
            get {
                return ResourceManager.GetString("OverviewTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerNameLbl {
            get {
                return ResourceManager.GetString("OwnerNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Remarks.
        /// </summary>
        public static string OwnersRemarksLbl {
            get {
                return ResourceManager.GetString("OwnersRemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner.
        /// </summary>
        public static string ProjectOwnerLb {
            get {
                return ResourceManager.GetString("ProjectOwnerLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title.
        /// </summary>
        public static string ProjectTitleLbl {
            get {
                return ResourceManager.GetString("ProjectTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Type.
        /// </summary>
        public static string ProjectTypeLbl {
            get {
                return ResourceManager.GetString("ProjectTypeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ProposalApprover_Closed {
            get {
                return ResourceManager.GetString("ProposalApprover_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapproved.
        /// </summary>
        public static string ProposalApprover_Disapproved {
            get {
                return ResourceManager.GetString("ProposalApprover_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-verification.
        /// </summary>
        public static string ProposalApprover_NoVerification {
            get {
                return ResourceManager.GetString("ProposalApprover_NoVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string ProposalApprover_Saved {
            get {
                return ResourceManager.GetString("ProposalApprover_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string ProposalApprover_Verified {
            get {
                return ResourceManager.GetString("ProposalApprover_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string ProposalDescLb {
            get {
                return ResourceManager.GetString("ProposalDescLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal Details.
        /// </summary>
        public static string ProposalDetailsHeader {
            get {
                return ResourceManager.GetString("ProposalDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qlik View Section.
        /// </summary>
        public static string QlikViewSectionHeader {
            get {
                return ResourceManager.GetString("QlikViewSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtnLbl {
            get {
                return ResourceManager.GetString("SaveBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Employee.
        /// </summary>
        public static string SearchEmployeeLbl {
            get {
                return ResourceManager.GetString("SearchEmployeeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Documents.
        /// </summary>
        public static string SupportingDocumentsLbl {
            get {
                return ResourceManager.GetString("SupportingDocumentsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string TicketNumberLbl {
            get {
                return ResourceManager.GetString("TicketNumberLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Dollar Impact.
        /// </summary>
        public static string TotalDollarImpactLbl {
            get {
                return ResourceManager.GetString("TotalDollarImpactLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update this proposal.
        /// </summary>
        public static string UpdateProposalbtn {
            get {
                return ResourceManager.GetString("UpdateProposalbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Changing the area/department beneficiary might change the cost-analyst approver..
        /// </summary>
        public static string updateProposalWarningMsg {
            get {
                return ResourceManager.GetString("updateProposalWarningMsg", resourceCulture);
            }
        }
    }
}
