//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAVINGS_v1.Resources.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESAVINGS_v1.Resources.Profile.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Description.
        /// </summary>
        public static string ActionDescriptionLbl {
            get {
                return ResourceManager.GetString("ActionDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active proposals.
        /// </summary>
        public static string ActiveProposalsHeader {
            get {
                return ResourceManager.GetString("ActiveProposalsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived Proposal (s).
        /// </summary>
        public static string ArchivedProposalsHeader {
            get {
                return ResourceManager.GetString("ArchivedProposalsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Proposal.
        /// </summary>
        public static string CreateNewProposalBtnLbl {
            get {
                return ResourceManager.GetString("CreateNewProposalBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your approval.
        /// </summary>
        public static string ForYourApprovalHeader {
            get {
                return ResourceManager.GetString("ForYourApprovalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of submission by status.
        /// </summary>
        public static string NumberOfSubmissionByStatusLbl {
            get {
                return ResourceManager.GetString("NumberOfSubmissionByStatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects assign to you.
        /// </summary>
        public static string ProjectsAssignToYouHeader {
            get {
                return ResourceManager.GetString("ProjectsAssignToYouHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string ProjectTypeLbl {
            get {
                return ResourceManager.GetString("ProjectTypeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLbl {
            get {
                return ResourceManager.GetString("StatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string SubmissionLbl {
            get {
                return ResourceManager.GetString("SubmissionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted By.
        /// </summary>
        public static string SubmittedByLbl {
            get {
                return ResourceManager.GetString("SubmittedByLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string TicketNumberLbl {
            get {
                return ResourceManager.GetString("TicketNumberLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleLbl {
            get {
                return ResourceManager.GetString("TitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your action item (s).
        /// </summary>
        public static string YourActionItemsHeader {
            get {
                return ResourceManager.GetString("YourActionItemsHeader", resourceCulture);
            }
        }
    }
}
